DROP VIEW IF EXISTS vw_recepcion_granel_consolidado;
DROP VIEW IF EXISTS vw_recepcion_mp_detallado;
DROP VIEW IF EXISTS vw_recepcion_ind_detallado;

CREATE VIEW vw_recepcion_mp_detallado AS
SELECT
    R.ID_RECEPCION,
    D.ID_DRECEPCION,
    R.ID_EMPRESA,
    R.ID_PLANTA,
    R.ID_TEMPORADA,
    D.FOLIO_DRECEPCION,
    D.FECHA_COSECHA_DRECEPCION AS FECHA_DETALLE,
    'Materia Prima' AS TIPO_PRODUCTO,
    IFNULL(ER.CODIGO_ESTANDAR, 'Sin Datos') AS CODIGO_ESTANDAR,
    IFNULL(ER.NOMBRE_ESTANDAR, 'Sin Datos') AS NOMBRE_ESTANDAR,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG_PRODUCTOR,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS NOMBRE_PRODUCTOR,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS NOMBRE_ESPECIES,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS NOMBRE_VESPECIES,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS ENVASE,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS NETO,
    IFNULL(D.KILOS_BRUTO_DRECEPCION, 0) AS BRUTO,
    R.NUMERO_RECEPCION,
    R.FECHA_RECEPCION,
    CASE R.TRECEPCION
        WHEN 1 THEN 'Desde Productor '
        WHEN 2 THEN 'Planta Externa'
        WHEN 3 THEN 'Desde Productor BDH'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    CASE
        WHEN R.TRECEPCION IN (1, 3) THEN IFNULL(CONCAT(ORIG_PROD.CSG_PRODUCTOR, ':', ORIG_PROD.NOMBRE_PRODUCTOR), 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    R.NUMERO_GUIA_RECEPCION,
    R.FECHA_GUIA_RECEPCION,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS NOMBRE_TMANEJO,
    CASE D.GASIFICADO_DRECEPCION
        WHEN 1 THEN 'SI'
        WHEN 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS GASIFICACION,
    IFNULL(TT1.NOMBRE_TTRATAMIENTO, 'Sin Datos') AS TRATAMIENTO1,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    R.PATENTE_CAMION,
    R.PATENTE_CARRO,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA,
    IFNULL(TT2.NOMBRE_TTRATAMIENTO, 'Sin Datos') AS CUARTEL
FROM fruta_recepcionmp R
INNER JOIN fruta_drecepcionmp D ON D.ID_RECEPCION = R.ID_RECEPCION AND D.ESTADO_REGISTRO = 1
LEFT JOIN fruta_productor PROD ON PROD.ID_PRODUCTOR = D.ID_PRODUCTOR
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN fruta_vespecies VES ON VES.ID_VESPECIES = D.ID_VESPECIES
LEFT JOIN fruta_especies ESP ON ESP.ID_ESPECIES = VES.ID_ESPECIES
LEFT JOIN estandar_erecepcion ER ON ER.ID_ESTANDAR = D.ID_ESTANDAR
LEFT JOIN fruta_tmanejo TM ON TM.ID_TMANEJO = D.ID_TMANEJO
LEFT JOIN fruta_tratamineto1 TT1 ON TT1.ID_TTRATAMIENTO = D.ID_TTRATAMIENTO1
LEFT JOIN fruta_tratamineto2 TT2 ON TT2.ID_TTRATAMIENTO = D.ID_TTRATAMIENTO2
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
WHERE R.ESTADO_REGISTRO = 1;

CREATE VIEW vw_recepcion_ind_detallado AS
SELECT
    R.ID_RECEPCION,
    D.ID_DRECEPCION,
    R.ID_EMPRESA,
    R.ID_PLANTA,
    R.ID_TEMPORADA,
    D.FOLIO_DRECEPCION,
    D.FECHA_EMBALADO_DRECEPCION AS FECHA_DETALLE,
    'Producto Industrial' AS TIPO_PRODUCTO,
    IFNULL(EI.CODIGO_ESTANDAR, 'Sin Datos') AS CODIGO_ESTANDAR,
    IFNULL(EI.NOMBRE_ESTANDAR, 'Sin Datos') AS NOMBRE_ESTANDAR,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG_PRODUCTOR,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS NOMBRE_PRODUCTOR,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS NOMBRE_ESPECIES,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS NOMBRE_VESPECIES,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS ENVASE,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS NETO,
    IFNULL(D.KILOS_BRUTO_DRECEPCION, 0) AS BRUTO,
    R.NUMERO_RECEPCION,
    R.FECHA_RECEPCION,
    CASE R.TRECEPCION
        WHEN 1 THEN 'Desde Productor '
        WHEN 2 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    CASE
        WHEN R.TRECEPCION = 1 THEN IFNULL(CONCAT(ORIG_PROD.CSG_PRODUCTOR, ':', ORIG_PROD.NOMBRE_PRODUCTOR), 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    R.NUMERO_GUIA_RECEPCION,
    R.FECHA_GUIA_RECEPCION,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS NOMBRE_TMANEJO,
    'Sin Datos' AS GASIFICACION,
    'Sin Datos' AS TRATAMIENTO1,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    R.PATENTE_CAMION,
    R.PATENTE_CARRO,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA,
    'Sin Datos' AS CUARTEL
FROM fruta_recepcionind R
INNER JOIN fruta_drecepcionind D ON D.ID_RECEPCION = R.ID_RECEPCION AND D.ESTADO_REGISTRO = 1
LEFT JOIN fruta_productor PROD ON PROD.ID_PRODUCTOR = D.ID_PRODUCTOR
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN fruta_vespecies VES ON VES.ID_VESPECIES = D.ID_VESPECIES
LEFT JOIN fruta_especies ESP ON ESP.ID_ESPECIES = VES.ID_ESPECIES
LEFT JOIN estandar_eindustrial EI ON EI.ID_ESTANDAR = D.ID_ESTANDAR
LEFT JOIN fruta_tmanejo TM ON TM.ID_TMANEJO = D.ID_TMANEJO
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
WHERE R.ESTADO_REGISTRO = 1;

CREATE VIEW vw_recepcion_granel_consolidado AS
SELECT * FROM vw_recepcion_ind_detallado
UNION ALL
SELECT * FROM vw_recepcion_mp_detallado;
