ALTER TABLE liquidacion_valor
    ADD COLUMN IF NOT EXISTS ESTADO_LIQUIDACION VARCHAR(20) NOT NULL DEFAULT 'LIQUIDADA' AFTER CONDICION_FLETE;

UPDATE liquidacion_valor
SET ESTADO_LIQUIDACION = 'LIQUIDADA'
WHERE ESTADO_REGISTRO = 1
AND (ESTADO_LIQUIDACION IS NULL OR ESTADO_LIQUIDACION = '');
