INSERT INTO fruta_calidad_parametro (
    TIPO_PARAMETRO,
    GRUPO_REPORTE,
    ETAPA,
    CODIGO_PARAMETRO,
    NOMBRE_PARAMETRO,
    UNIDAD_MEDIDA,
    VALOR_MINIMO,
    VALOR_MAXIMO,
    VALOR_REFERENCIA,
    ES_REQUERIDO,
    ORDEN,
    ID_EMPRESA,
    ID_TEMPORADA,
    ID_ESPECIES,
    ID_USUARIOI,
    ID_USUARIOM,
    ESTADO_REGISTRO
)
SELECT
    P.TIPO_PARAMETRO,
    P.GRUPO_REPORTE,
    E.ETAPA_NUEVA,
    REPLACE(P.CODIGO_PARAMETRO, 'REC-', E.PREFIJO),
    P.NOMBRE_PARAMETRO,
    P.UNIDAD_MEDIDA,
    P.VALOR_MINIMO,
    P.VALOR_MAXIMO,
    P.VALOR_REFERENCIA,
    P.ES_REQUERIDO,
    P.ORDEN,
    P.ID_EMPRESA,
    P.ID_TEMPORADA,
    P.ID_ESPECIES,
    P.ID_USUARIOI,
    P.ID_USUARIOM,
    1
FROM fruta_calidad_parametro P
JOIN (
    SELECT 'PROCESO' ETAPA_NUEVA, 'PRO-' PREFIJO
    UNION ALL SELECT 'EXPORTACION', 'EXP-'
) E
WHERE P.ETAPA = 'RECEPCION'
AND P.ESTADO_REGISTRO = 1
AND P.GRUPO_REPORTE IN ('CALIBRES', 'PRESIONES', 'PARAMETROS', 'DEFECTOS_CONDICION', 'DEFECTOS_CALIDAD')
AND NOT EXISTS (
    SELECT 1
    FROM fruta_calidad_parametro X
    WHERE X.ID_EMPRESA = P.ID_EMPRESA
    AND X.ID_TEMPORADA = P.ID_TEMPORADA
    AND X.ID_ESPECIES = P.ID_ESPECIES
    AND X.ETAPA = E.ETAPA_NUEVA
    AND X.GRUPO_REPORTE = P.GRUPO_REPORTE
    AND X.NOMBRE_PARAMETRO = P.NOMBRE_PARAMETRO
    AND X.ESTADO_REGISTRO = 1
);
