CREATE TABLE IF NOT EXISTS fruta_calidad_regla_resolucion (
    ID_CALIDAD_REGLA_RESOLUCION BIGINT(20) NOT NULL AUTO_INCREMENT,
    NOMBRE_REGLA VARCHAR(150) NOT NULL DEFAULT '% ESTIMADO EXPORTACION',
    RESULTADO VARCHAR(30) NOT NULL,
    VALOR_MINIMO DECIMAL(12,4) NOT NULL,
    VALOR_MAXIMO DECIMAL(12,4) NOT NULL,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ID_TEMPORADA BIGINT(20) NOT NULL,
    ID_ESPECIES BIGINT(20) NOT NULL,
    ID_USUARIOI BIGINT(20) NULL,
    ID_USUARIOM BIGINT(20) NULL,
    INGRESO DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICACION DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CALIDAD_REGLA_RESOLUCION),
    KEY IDX_CALIDAD_REGLA_RESOLUCION_CONTEXTO (ID_EMPRESA, ID_TEMPORADA, ID_ESPECIES, ESTADO_REGISTRO),
    KEY IDX_CALIDAD_REGLA_RESOLUCION_RANGO (VALOR_MINIMO, VALOR_MAXIMO, RESULTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
