ALTER TABLE fruta_calidad_control
    ADD COLUMN IF NOT EXISTS ESTADO_CONTROL VARCHAR(20) NOT NULL DEFAULT 'ABIERTO' AFTER RESULTADO_GENERAL,
    ADD COLUMN IF NOT EXISTS FECHA_CIERRE DATE NULL AFTER OBSERVACION,
    ADD COLUMN IF NOT EXISTS HORA_CIERRE TIME NULL AFTER FECHA_CIERRE,
    ADD COLUMN IF NOT EXISTS ID_USUARIO_CIERRE BIGINT(20) NULL AFTER HORA_CIERRE,
    ADD COLUMN IF NOT EXISTS OBSERVACION_CIERRE VARCHAR(500) NULL AFTER ID_USUARIO_CIERRE,
    ADD KEY IF NOT EXISTS IDX_CALIDAD_CONTROL_ESTADO (ESTADO_CONTROL, ETAPA, ESTADO_REGISTRO);
