DROP VIEW IF EXISTS vw_recepcion_mp_listado;
DROP VIEW IF EXISTS vw_recepcion_ind_listado;

CREATE VIEW vw_recepcion_mp_listado AS
SELECT
    R.*,
    R.FECHA_GUIA_RECEPCION AS FECHA_GUIA,
    R.FECHA_RECEPCION AS FECHA,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    WEEKOFYEAR(R.FECHA_RECEPCION) AS SEMANAISO,
    WEEKOFYEAR(R.FECHA_GUIA_RECEPCION) AS SEMANAGUIAISO,
    DATE_FORMAT(R.INGRESO, '%Y-%m-%d') AS INGRESO_FORMATO,
    DATE_FORMAT(R.MODIFICACION, '%Y-%m-%d') AS MODIFICACION_FORMATO,
    IFNULL(R.CANTIDAD_ENVASE_RECEPCION, 0) AS ENVASE,
    IFNULL(R.KILOS_NETO_RECEPCION, 0) AS NETO,
    IFNULL(R.KILOS_BRUTO_RECEPCION, 0) AS BRUTO,
    IFNULL(R.TOTAL_KILOS_GUIA_RECEPCION, 0) AS GUIA,
    CASE R.TRECEPCION
        WHEN 1 THEN 'Desde Productor '
        WHEN 2 THEN 'Planta Externa'
        WHEN 3 THEN 'Desde Productor BDH'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    CASE
        WHEN R.TRECEPCION IN (1, 3) THEN IFNULL(ORIG_PROD.CSG_PRODUCTOR, 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.CODIGO_SAG_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS CSGCSP_ORIGEN,
    CASE
        WHEN R.TRECEPCION IN (1, 3) THEN IFNULL(ORIG_PROD.NOMBRE_PRODUCTOR, 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA
FROM fruta_recepcionmp R
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
WHERE R.ESTADO_REGISTRO = 1;

CREATE VIEW vw_recepcion_ind_listado AS
SELECT
    R.*,
    R.FECHA_GUIA_RECEPCION AS FECHA_GUIA,
    R.FECHA_RECEPCION AS FECHA,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    WEEKOFYEAR(R.FECHA_RECEPCION) AS SEMANAISO,
    WEEKOFYEAR(R.FECHA_GUIA_RECEPCION) AS SEMANAGUIAISO,
    DATE_FORMAT(R.INGRESO, '%Y-%m-%d') AS INGRESO_FORMATO,
    DATE_FORMAT(R.MODIFICACION, '%Y-%m-%d') AS MODIFICACION_FORMATO,
    IFNULL(R.CANTIDAD_ENVASE_RECEPCION, 0) AS ENVASE,
    IFNULL(R.KILOS_NETO_RECEPCION, 0) AS NETO,
    IFNULL(R.KILOS_BRUTO_RECEPCION, 0) AS BRUTO,
    IFNULL(R.TOTAL_KILOS_GUIA_RECEPCION, 0) AS GUIA,
    CASE R.TRECEPCION
        WHEN 1 THEN 'Desde Productor '
        WHEN 2 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    CASE
        WHEN R.TRECEPCION = 1 THEN IFNULL(ORIG_PROD.CSG_PRODUCTOR, 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.CODIGO_SAG_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS CSGCSP_ORIGEN,
    CASE
        WHEN R.TRECEPCION = 1 THEN IFNULL(ORIG_PROD.NOMBRE_PRODUCTOR, 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA
FROM fruta_recepcionind R
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
WHERE R.ESTADO_REGISTRO = 1;
