DROP VIEW IF EXISTS view_despachos;

CREATE VIEW view_despachos AS
SELECT
    'DESPACHO_MP' AS TIPO_REPORTE,
    exi.ID_EXIMATERIAPRIMA AS ID_DETALLE,
    des.ID_DESPACHO AS ID_DESPACHO,
    NULL AS ID_DESPACHOEX,
    exi.FOLIO_EXIMATERIAPRIMA AS FOLIO,
    exi.FOLIO_AUXILIAR_EXIMATERIAPRIMA AS FOLIO_AUXILIAR,
    exi.FECHA_COSECHA_EXIMATERIAPRIMA AS FECHA_DETALLE,
    'Materia Prima' AS TIPO_PRODUCTO,
    est.CODIGO_ESTANDAR AS CODIGO_ESTANDAR,
    est.NOMBRE_ESTANDAR AS NOMBRE_ESTANDAR,
    prod.CSG_PRODUCTOR AS CSG,
    prod.NOMBRE_PRODUCTOR AS PRODUCTOR,
    esp.NOMBRE_ESPECIES AS ESPECIE,
    vesp.NOMBRE_VESPECIES AS VARIEDAD,
    exi.CANTIDAD_ENVASE_EXIMATERIAPRIMA AS ENVASE,
    exi.KILOS_NETO_EXIMATERIAPRIMA AS NETO,
    NULL AS PORCENTAJE_DESHIDRATACION,
    NULL AS KILOS_DESHIDRATACION,
    exi.KILOS_BRUTO_EXIMATERIAPRIMA AS BRUTO,
    des.NUMERO_DESPACHO AS NUMERO_DESPACHO,
    des.FECHA_DESPACHO AS FECHA_DESPACHO,
    des.NUMERO_GUIA_DESPACHO AS NUMERO_GUIA_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN 'Interplanta'
        WHEN 2 THEN 'Devolucion Productor'
        WHEN 3 THEN 'Venta'
        WHEN 4 THEN 'Despacho de Descarte'
        WHEN 5 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN planta2.NOMBRE_PLANTA
        WHEN 2 THEN prodDes.NOMBRE_PRODUCTOR
        WHEN 3 THEN comprador.NOMBRE_COMPRADOR
        WHEN 5 THEN planta3.NOMBRE_PLANTA
        ELSE NULL
    END AS DESTINO,
    tm.NOMBRE_TMANEJO AS TIPO_MANEJO,
    NULL AS TIPO_CALIBRE,
    NULL AS TIPO_EMBALAJE,
    NULL AS STOCK,
    NULL AS EMBOLSADO,
    IF(exi.GASIFICADO = 1, 'Si', IF(exi.GASIFICADO = 0, 'No', NULL)) AS GASIFICACION,
    NULL AS PREFRIO,
    trans.NOMBRE_TRANSPORTE AS TRANSPORTE,
    cond.NOMBRE_CONDUCTOR AS NOMBRE_CONDUCTOR,
    des.PATENTE_CAMION AS PATENTE_CAMION,
    des.PATENTE_CARRO AS PATENTE_CARRO,
    WEEK(des.FECHA_DESPACHO, 3) AS SEMANA_DESPACHO,
    emp.NOMBRE_EMPRESA AS EMPRESA,
    planta.NOMBRE_PLANTA AS PLANTA,
    temp.NOMBRE_TEMPORADA AS TEMPORADA,
    NULL AS PRECIO_UNITARIO,
    NULL AS VALOR_VENTA,
    NULL AS TOTAL_PRECIO_DESPACHO,
    NULL AS FOB_REFERENCIA_CAJA,
    NULL AS FOB_REFERENCIA_KG,
    NULL AS FOB_VENTA_CAJA,
    NULL AS FOB_VENTA_KG,
    NULL AS VENTA_USD,
    NULL AS VENTA_USD_BRUTO,
    NULL AS VENTA_USD_NETO,
    NULL AS RETORNO_NETO,
    NULL AS FOB_FINAL_KG,
    NULL AS FOB_FINAL_CAJA,
    NULL AS NUMERO_VALOR,
    NULL AS FECHA_VALOR,
    NULL AS ESTADO_LIQUIDACION,
    NULL AS PRECIO_CAJA_INVOICE,
    NULL AS TOTAL_LINEA_INVOICE,
    NULL AS NUMERO_INVOICE,
    NULL AS MONEDA_INVOICE,
    NULL AS NREFERENCIA_ICARGA,
    NULL AS CLIENTE,
    NULL AS MERCADO,
    NULL AS CONTENEDOR,
    NULL AS BL_AWB,
    NULL AS RECIBIDOR_FINAL,
    NULL AS TIPO_EMBARQUE,
    NULL AS NAVE,
    NULL AS NUMERO_VIAJE,
    NULL AS FECHA_ETD,
    NULL AS FECHA_ETA,
    NULL AS FECHA_REAL_ETD,
    NULL AS FECHA_REAL_ETA,
    NULL AS TERMOGRAFO_DESPACHO,
    NULL AS TERMOGRAFO_PALLET,
    des.ID_EMPRESA,
    des.ID_PLANTA,
    des.ID_TEMPORADA,
    esp.ID_ESPECIES,
    exi.ID_VESPECIES,
    exi.ID_PRODUCTOR,
    NULL AS ID_ICARGA
FROM fruta_eximateriaprima exi
INNER JOIN fruta_despachomp des ON des.ID_DESPACHO = exi.ID_DESPACHO
LEFT JOIN estandar_erecepcion est ON est.ID_ESTANDAR = exi.ID_ESTANDAR
LEFT JOIN fruta_productor prod ON prod.ID_PRODUCTOR = exi.ID_PRODUCTOR
LEFT JOIN fruta_productor prodDes ON prodDes.ID_PRODUCTOR = des.ID_PRODUCTOR
LEFT JOIN fruta_vespecies vesp ON vesp.ID_VESPECIES = exi.ID_VESPECIES
LEFT JOIN fruta_especies esp ON esp.ID_ESPECIES = vesp.ID_ESPECIES
LEFT JOIN fruta_tmanejo tm ON tm.ID_TMANEJO = exi.ID_TMANEJO
LEFT JOIN transporte_transporte trans ON trans.ID_TRANSPORTE = des.ID_TRANSPORTE
LEFT JOIN transporte_conductor cond ON cond.ID_CONDUCTOR = des.ID_CONDUCTOR
LEFT JOIN fruta_comprador comprador ON comprador.ID_COMPRADOR = des.ID_COMPRADOR
LEFT JOIN principal_empresa emp ON emp.ID_EMPRESA = des.ID_EMPRESA
LEFT JOIN principal_planta planta ON planta.ID_PLANTA = des.ID_PLANTA
LEFT JOIN principal_planta planta2 ON planta2.ID_PLANTA = des.ID_PLANTA2
LEFT JOIN principal_planta planta3 ON planta3.ID_PLANTA = des.ID_PLANTA3
LEFT JOIN principal_temporada temp ON temp.ID_TEMPORADA = des.ID_TEMPORADA
WHERE exi.ESTADO_REGISTRO = 1
  AND des.ESTADO_REGISTRO = 1

UNION ALL

SELECT
    'DESPACHO_IND' AS TIPO_REPORTE,
    exi.ID_EXIINDUSTRIAL AS ID_DETALLE,
    des.ID_DESPACHO AS ID_DESPACHO,
    NULL AS ID_DESPACHOEX,
    exi.FOLIO_EXIINDUSTRIAL AS FOLIO,
    exi.FOLIO_AUXILIAR_EXIINDUSTRIAL AS FOLIO_AUXILIAR,
    exi.FECHA_EMBALADO_EXIINDUSTRIAL AS FECHA_DETALLE,
    'Industrial' AS TIPO_PRODUCTO,
    est.CODIGO_ESTANDAR AS CODIGO_ESTANDAR,
    est.NOMBRE_ESTANDAR AS NOMBRE_ESTANDAR,
    prod.CSG_PRODUCTOR AS CSG,
    prod.NOMBRE_PRODUCTOR AS PRODUCTOR,
    esp.NOMBRE_ESPECIES AS ESPECIE,
    vesp.NOMBRE_VESPECIES AS VARIEDAD,
    exi.CANTIDAD_ENVASE_EXIINDUSTRIAL AS ENVASE,
    exi.KILOS_NETO_EXIINDUSTRIAL AS NETO,
    exi.PDESHIDRATACION_EXIINDUSTRIAL AS PORCENTAJE_DESHIDRATACION,
    exi.KILOS_DESHIRATACION_EXIINDUSTRIAL AS KILOS_DESHIDRATACION,
    exi.KILOS_BRUTO_EXIINDUSTRIAL AS BRUTO,
    des.NUMERO_DESPACHO AS NUMERO_DESPACHO,
    des.FECHA_DESPACHO AS FECHA_DESPACHO,
    des.NUMERO_GUIA_DESPACHO AS NUMERO_GUIA_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN 'Interplanta'
        WHEN 2 THEN 'Devolucion Productor'
        WHEN 3 THEN 'Venta'
        WHEN 4 THEN 'Despacho de Descarte'
        WHEN 5 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN planta2.NOMBRE_PLANTA
        WHEN 2 THEN prodDes.NOMBRE_PRODUCTOR
        WHEN 3 THEN comprador.NOMBRE_COMPRADOR
        WHEN 5 THEN planta3.NOMBRE_PLANTA
        ELSE NULL
    END AS DESTINO,
    tm.NOMBRE_TMANEJO AS TIPO_MANEJO,
    COALESCE(tcind.NOMBRE_TCALIBREIND, tc.NOMBRE_TCALIBRE) AS TIPO_CALIBRE,
    tem.NOMBRE_TEMBALAJE AS TIPO_EMBALAJE,
    exi.STOCK AS STOCK,
    IF(exi.EMBOLSADO = 1, 'Si', IF(exi.EMBOLSADO = 0, 'No', NULL)) AS EMBOLSADO,
    IF(exi.GASIFICADO = 1, 'Si', IF(exi.GASIFICADO = 0, 'No', NULL)) AS GASIFICACION,
    IF(exi.PREFRIO = 1, 'Si', IF(exi.PREFRIO = 0, 'No', NULL)) AS PREFRIO,
    trans.NOMBRE_TRANSPORTE AS TRANSPORTE,
    cond.NOMBRE_CONDUCTOR AS NOMBRE_CONDUCTOR,
    des.PATENTE_CAMION AS PATENTE_CAMION,
    des.PATENTE_CARRO AS PATENTE_CARRO,
    WEEK(des.FECHA_DESPACHO, 3) AS SEMANA_DESPACHO,
    emp.NOMBRE_EMPRESA AS EMPRESA,
    planta.NOMBRE_PLANTA AS PLANTA,
    temp.NOMBRE_TEMPORADA AS TEMPORADA,
    exi.PRECIO_KILO AS PRECIO_UNITARIO,
    ROUND(IFNULL(exi.PRECIO_KILO, 0) * IFNULL(exi.KILOS_NETO_EXIINDUSTRIAL, 0), 2) AS VALOR_VENTA,
    des.TOTAL_PRECIO AS TOTAL_PRECIO_DESPACHO,
    NULL AS FOB_REFERENCIA_CAJA,
    NULL AS FOB_REFERENCIA_KG,
    NULL AS FOB_VENTA_CAJA,
    NULL AS FOB_VENTA_KG,
    NULL AS VENTA_USD,
    NULL AS VENTA_USD_BRUTO,
    NULL AS VENTA_USD_NETO,
    NULL AS RETORNO_NETO,
    NULL AS FOB_FINAL_KG,
    NULL AS FOB_FINAL_CAJA,
    NULL AS NUMERO_VALOR,
    NULL AS FECHA_VALOR,
    NULL AS ESTADO_LIQUIDACION,
    NULL AS PRECIO_CAJA_INVOICE,
    NULL AS TOTAL_LINEA_INVOICE,
    NULL AS NUMERO_INVOICE,
    NULL AS MONEDA_INVOICE,
    NULL AS NREFERENCIA_ICARGA,
    NULL AS CLIENTE,
    NULL AS MERCADO,
    NULL AS CONTENEDOR,
    NULL AS BL_AWB,
    NULL AS RECIBIDOR_FINAL,
    NULL AS TIPO_EMBARQUE,
    NULL AS NAVE,
    NULL AS NUMERO_VIAJE,
    NULL AS FECHA_ETD,
    NULL AS FECHA_ETA,
    NULL AS FECHA_REAL_ETD,
    NULL AS FECHA_REAL_ETA,
    NULL AS TERMOGRAFO_DESPACHO,
    NULL AS TERMOGRAFO_PALLET,
    des.ID_EMPRESA,
    des.ID_PLANTA,
    des.ID_TEMPORADA,
    esp.ID_ESPECIES,
    exi.ID_VESPECIES,
    exi.ID_PRODUCTOR,
    NULL AS ID_ICARGA
FROM fruta_exiindustrial exi
INNER JOIN fruta_despachoind des ON des.ID_DESPACHO = exi.ID_DESPACHO
LEFT JOIN estandar_eindustrial est ON est.ID_ESTANDAR = exi.ID_ESTANDAR
LEFT JOIN fruta_productor prod ON prod.ID_PRODUCTOR = exi.ID_PRODUCTOR
LEFT JOIN fruta_productor prodDes ON prodDes.ID_PRODUCTOR = des.ID_PRODUCTOR
LEFT JOIN fruta_vespecies vesp ON vesp.ID_VESPECIES = exi.ID_VESPECIES
LEFT JOIN fruta_especies esp ON esp.ID_ESPECIES = vesp.ID_ESPECIES
LEFT JOIN fruta_tmanejo tm ON tm.ID_TMANEJO = exi.ID_TMANEJO
LEFT JOIN fruta_tcalibre tc ON tc.ID_TCALIBRE = exi.ID_TCALIBRE
LEFT JOIN fruta_tcalibreind tcind ON tcind.ID_TCALIBREIND = exi.ID_TCALIBRE
LEFT JOIN fruta_tembalaje tem ON tem.ID_TEMBALAJE = exi.ID_TEMBALAJE
LEFT JOIN transporte_transporte trans ON trans.ID_TRANSPORTE = des.ID_TRANSPORTE
LEFT JOIN transporte_conductor cond ON cond.ID_CONDUCTOR = des.ID_CONDUCTOR
LEFT JOIN fruta_comprador comprador ON comprador.ID_COMPRADOR = des.ID_COMPRADOR
LEFT JOIN principal_empresa emp ON emp.ID_EMPRESA = des.ID_EMPRESA
LEFT JOIN principal_planta planta ON planta.ID_PLANTA = des.ID_PLANTA
LEFT JOIN principal_planta planta2 ON planta2.ID_PLANTA = des.ID_PLANTA2
LEFT JOIN principal_planta planta3 ON planta3.ID_PLANTA = des.ID_PLANTA3
LEFT JOIN principal_temporada temp ON temp.ID_TEMPORADA = des.ID_TEMPORADA
WHERE exi.ESTADO_REGISTRO = 1
  AND exi.ESTADO BETWEEN 3 AND 5
  AND des.ESTADO_REGISTRO = 1

UNION ALL

SELECT
    'DESPACHO_PT' AS TIPO_REPORTE,
    exi.ID_EXIEXPORTACION AS ID_DETALLE,
    des.ID_DESPACHO AS ID_DESPACHO,
    NULL AS ID_DESPACHOEX,
    exi.FOLIO_EXIEXPORTACION AS FOLIO,
    exi.FOLIO_AUXILIAR_EXIEXPORTACION AS FOLIO_AUXILIAR,
    exi.FECHA_EMBALADO_EXIEXPORTACION AS FECHA_DETALLE,
    'Producto Terminado' AS TIPO_PRODUCTO,
    est.CODIGO_ESTANDAR AS CODIGO_ESTANDAR,
    est.NOMBRE_ESTANDAR AS NOMBRE_ESTANDAR,
    prod.CSG_PRODUCTOR AS CSG,
    prod.NOMBRE_PRODUCTOR AS PRODUCTOR,
    esp.NOMBRE_ESPECIES AS ESPECIE,
    vesp.NOMBRE_VESPECIES AS VARIEDAD,
    exi.CANTIDAD_ENVASE_EXIEXPORTACION AS ENVASE,
    exi.KILOS_NETO_EXIEXPORTACION AS NETO,
    exi.PDESHIDRATACION_EXIEXPORTACION AS PORCENTAJE_DESHIDRATACION,
    exi.KILOS_DESHIRATACION_EXIEXPORTACION AS KILOS_DESHIDRATACION,
    exi.KILOS_BRUTO_EXIEXPORTACION AS BRUTO,
    des.NUMERO_DESPACHO AS NUMERO_DESPACHO,
    des.FECHA_DESPACHO AS FECHA_DESPACHO,
    des.NUMERO_GUIA_DESPACHO AS NUMERO_GUIA_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN 'Interplanta'
        WHEN 2 THEN 'Devolucion Productor'
        WHEN 3 THEN 'Venta'
        WHEN 4 THEN 'Despacho de Descarte'
        WHEN 5 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_DESPACHO,
    CASE des.TDESPACHO
        WHEN 1 THEN planta2.NOMBRE_PLANTA
        WHEN 2 THEN prodDes.NOMBRE_PRODUCTOR
        WHEN 3 THEN comprador.NOMBRE_COMPRADOR
        WHEN 5 THEN planta3.NOMBRE_PLANTA
        ELSE NULL
    END AS DESTINO,
    tm.NOMBRE_TMANEJO AS TIPO_MANEJO,
    tc.NOMBRE_TCALIBRE AS TIPO_CALIBRE,
    tem.NOMBRE_TEMBALAJE AS TIPO_EMBALAJE,
    exi.STOCK AS STOCK,
    IF(exi.EMBOLSADO = 1, 'Si', IF(exi.EMBOLSADO = 0, 'No', NULL)) AS EMBOLSADO,
    IF(exi.GASIFICADO = 1, 'Si', IF(exi.GASIFICADO = 0, 'No', NULL)) AS GASIFICACION,
    IF(exi.PREFRIO = 1, 'Si', IF(exi.PREFRIO = 0, 'No', NULL)) AS PREFRIO,
    trans.NOMBRE_TRANSPORTE AS TRANSPORTE,
    cond.NOMBRE_CONDUCTOR AS NOMBRE_CONDUCTOR,
    des.PATENTE_CAMION AS PATENTE_CAMION,
    des.PATENTE_CARRO AS PATENTE_CARRO,
    WEEK(des.FECHA_DESPACHO, 3) AS SEMANA_DESPACHO,
    emp.NOMBRE_EMPRESA AS EMPRESA,
    planta.NOMBRE_PLANTA AS PLANTA,
    temp.NOMBRE_TEMPORADA AS TEMPORADA,
    exi.PRECIO_PALLET AS PRECIO_UNITARIO,
    ROUND(IFNULL(exi.PRECIO_PALLET, 0) * IFNULL(exi.CANTIDAD_ENVASE_EXIEXPORTACION, 0), 2) AS VALOR_VENTA,
    des.TOTAL_PRECIO AS TOTAL_PRECIO_DESPACHO,
    NULL AS FOB_REFERENCIA_CAJA,
    NULL AS FOB_REFERENCIA_KG,
    NULL AS FOB_VENTA_CAJA,
    NULL AS FOB_VENTA_KG,
    NULL AS VENTA_USD,
    NULL AS VENTA_USD_BRUTO,
    NULL AS VENTA_USD_NETO,
    NULL AS RETORNO_NETO,
    NULL AS FOB_FINAL_KG,
    NULL AS FOB_FINAL_CAJA,
    NULL AS NUMERO_VALOR,
    NULL AS FECHA_VALOR,
    NULL AS ESTADO_LIQUIDACION,
    NULL AS PRECIO_CAJA_INVOICE,
    NULL AS TOTAL_LINEA_INVOICE,
    NULL AS NUMERO_INVOICE,
    NULL AS MONEDA_INVOICE,
    NULL AS NREFERENCIA_ICARGA,
    NULL AS CLIENTE,
    NULL AS MERCADO,
    NULL AS CONTENEDOR,
    NULL AS BL_AWB,
    NULL AS RECIBIDOR_FINAL,
    NULL AS TIPO_EMBARQUE,
    NULL AS NAVE,
    NULL AS NUMERO_VIAJE,
    NULL AS FECHA_ETD,
    NULL AS FECHA_ETA,
    NULL AS FECHA_REAL_ETD,
    NULL AS FECHA_REAL_ETA,
    NULL AS TERMOGRAFO_DESPACHO,
    exi.N_TERMOGRAFO AS TERMOGRAFO_PALLET,
    des.ID_EMPRESA,
    des.ID_PLANTA,
    des.ID_TEMPORADA,
    esp.ID_ESPECIES,
    exi.ID_VESPECIES,
    exi.ID_PRODUCTOR,
    exi.ID_ICARGA
FROM fruta_exiexportacion exi
INNER JOIN fruta_despachopt des ON des.ID_DESPACHO = exi.ID_DESPACHO
LEFT JOIN estandar_eexportacion est ON est.ID_ESTANDAR = exi.ID_ESTANDAR
LEFT JOIN fruta_productor prod ON prod.ID_PRODUCTOR = exi.ID_PRODUCTOR
LEFT JOIN fruta_productor prodDes ON prodDes.ID_PRODUCTOR = des.ID_PRODUCTOR
LEFT JOIN fruta_vespecies vesp ON vesp.ID_VESPECIES = exi.ID_VESPECIES
LEFT JOIN fruta_especies esp ON esp.ID_ESPECIES = vesp.ID_ESPECIES
LEFT JOIN fruta_tmanejo tm ON tm.ID_TMANEJO = exi.ID_TMANEJO
LEFT JOIN fruta_tcalibre tc ON tc.ID_TCALIBRE = exi.ID_TCALIBRE
LEFT JOIN fruta_tembalaje tem ON tem.ID_TEMBALAJE = exi.ID_TEMBALAJE
LEFT JOIN transporte_transporte trans ON trans.ID_TRANSPORTE = des.ID_TRANSPORTE
LEFT JOIN transporte_conductor cond ON cond.ID_CONDUCTOR = des.ID_CONDUCTOR
LEFT JOIN fruta_comprador comprador ON comprador.ID_COMPRADOR = des.ID_COMPRADOR
LEFT JOIN principal_empresa emp ON emp.ID_EMPRESA = des.ID_EMPRESA
LEFT JOIN principal_planta planta ON planta.ID_PLANTA = des.ID_PLANTA
LEFT JOIN principal_planta planta2 ON planta2.ID_PLANTA = des.ID_PLANTA2
LEFT JOIN principal_planta planta3 ON planta3.ID_PLANTA = des.ID_PLANTA3
LEFT JOIN principal_temporada temp ON temp.ID_TEMPORADA = des.ID_TEMPORADA
WHERE exi.ESTADO_REGISTRO = 1
  AND des.ESTADO_REGISTRO = 1

UNION ALL

SELECT
    'DESPACHO_EXPO' AS TIPO_REPORTE,
    exi.ID_EXIEXPORTACION AS ID_DETALLE,
    NULL AS ID_DESPACHO,
    des.ID_DESPACHOEX AS ID_DESPACHOEX,
    exi.FOLIO_EXIEXPORTACION AS FOLIO,
    exi.FOLIO_AUXILIAR_EXIEXPORTACION AS FOLIO_AUXILIAR,
    exi.FECHA_EMBALADO_EXIEXPORTACION AS FECHA_DETALLE,
    'Exportacion' AS TIPO_PRODUCTO,
    est.CODIGO_ESTANDAR AS CODIGO_ESTANDAR,
    est.NOMBRE_ESTANDAR AS NOMBRE_ESTANDAR,
    prod.CSG_PRODUCTOR AS CSG,
    prod.NOMBRE_PRODUCTOR AS PRODUCTOR,
    esp.NOMBRE_ESPECIES AS ESPECIE,
    vesp.NOMBRE_VESPECIES AS VARIEDAD,
    exi.CANTIDAD_ENVASE_EXIEXPORTACION AS ENVASE,
    exi.KILOS_NETO_EXIEXPORTACION AS NETO,
    exi.PDESHIDRATACION_EXIEXPORTACION AS PORCENTAJE_DESHIDRATACION,
    exi.KILOS_DESHIRATACION_EXIEXPORTACION AS KILOS_DESHIDRATACION,
    exi.KILOS_BRUTO_EXIEXPORTACION AS BRUTO,
    des.NUMERO_DESPACHOEX AS NUMERO_DESPACHO,
    des.FECHA_DESPACHOEX AS FECHA_DESPACHO,
    des.NUMERO_GUIA_DESPACHOEX AS NUMERO_GUIA_DESPACHO,
    'Exportacion' AS TIPO_DESPACHO,
    dfinal.NOMBRE_DFINAL AS DESTINO,
    tm.NOMBRE_TMANEJO AS TIPO_MANEJO,
    tc.NOMBRE_TCALIBRE AS TIPO_CALIBRE,
    tem.NOMBRE_TEMBALAJE AS TIPO_EMBALAJE,
    exi.STOCK AS STOCK,
    IF(exi.EMBOLSADO = 1, 'Si', IF(exi.EMBOLSADO = 0, 'No', NULL)) AS EMBOLSADO,
    IF(exi.GASIFICADO = 1, 'Si', IF(exi.GASIFICADO = 0, 'No', NULL)) AS GASIFICACION,
    IF(exi.PREFRIO = 1, 'Si', IF(exi.PREFRIO = 0, 'No', NULL)) AS PREFRIO,
    trans.NOMBRE_TRANSPORTE AS TRANSPORTE,
    cond.NOMBRE_CONDUCTOR AS NOMBRE_CONDUCTOR,
    des.PATENTE_CAMION AS PATENTE_CAMION,
    des.PATENTE_CARRO AS PATENTE_CARRO,
    WEEK(des.FECHA_DESPACHOEX, 3) AS SEMANA_DESPACHO,
    emp.NOMBRE_EMPRESA AS EMPRESA,
    planta.NOMBRE_PLANTA AS PLANTA,
    temp.NOMBRE_TEMPORADA AS TEMPORADA,
    COALESCE(liq.FOB_VENTA_CAJA, inv.PRECIO_CAJA_INVOICE, exi.PRECIO_PALLET) AS PRECIO_UNITARIO,
    ROUND(COALESCE(liq.VENTA_USD_NETO, liq.VENTA_USD, inv.TOTAL_LINEA_INVOICE, IFNULL(exi.PRECIO_PALLET, 0) * IFNULL(exi.CANTIDAD_ENVASE_EXIEXPORTACION, 0)), 2) AS VALOR_VENTA,
    NULL AS TOTAL_PRECIO_DESPACHO,
    liq.FOB_REFERENCIA_CAJA AS FOB_REFERENCIA_CAJA,
    liq.FOB_REFERENCIA_KG AS FOB_REFERENCIA_KG,
    liq.FOB_VENTA_CAJA AS FOB_VENTA_CAJA,
    liq.FOB_VENTA_KG AS FOB_VENTA_KG,
    liq.VENTA_USD AS VENTA_USD,
    liq.VENTA_USD_BRUTO AS VENTA_USD_BRUTO,
    liq.VENTA_USD_NETO AS VENTA_USD_NETO,
    liq.RETORNO_NETO AS RETORNO_NETO,
    liq.FOB_FINAL_KG AS FOB_FINAL_KG,
    liq.FOB_FINAL_CAJA AS FOB_FINAL_CAJA,
    liq.NUMERO_VALOR AS NUMERO_VALOR,
    liq.FECHA_VALOR AS FECHA_VALOR,
    liq.ESTADO_LIQUIDACION AS ESTADO_LIQUIDACION,
    inv.PRECIO_CAJA_INVOICE AS PRECIO_CAJA_INVOICE,
    inv.TOTAL_LINEA_INVOICE AS TOTAL_LINEA_INVOICE,
    inv.NUMERO_INVOICE AS NUMERO_INVOICE,
    inv.MONEDA_INVOICE AS MONEDA_INVOICE,
    ic.NREFERENCIA_ICARGA AS NREFERENCIA_ICARGA,
    broker.NOMBRE_BROKER AS CLIENTE,
    mercado.NOMBRE_MERCADO AS MERCADO,
    COALESCE(des.NUMERO_CONTENEDOR_DESPACHOEX, ic.NCONTENEDOR_ICARGA) AS CONTENEDOR,
    ic.BOLAWBCRT_ICARGA AS BL_AWB,
    rfinal.NOMBRE_RFINAL AS RECIBIDOR_FINAL,
    CASE COALESCE(des.TEMBARQUE_DESPACHOEX, ic.TEMBARQUE_ICARGA)
        WHEN 1 THEN 'Maritimo'
        WHEN 2 THEN 'Aereo'
        WHEN 3 THEN 'Terrestre'
        ELSE NULL
    END AS TIPO_EMBARQUE,
    COALESCE(des.NAVE_DESPACHOEX, ic.NAVE_ICARGA) AS NAVE,
    COALESCE(des.NVIAJE_DESPACHOEX, ic.NVIAJE_ICARGA) AS NUMERO_VIAJE,
    COALESCE(des.FECHAETD_DESPACHOEX, ic.FECHAETD_ICARGA) AS FECHA_ETD,
    COALESCE(des.FECHAETA_DESPACHOEX, ic.FECHAETA_ICARGA) AS FECHA_ETA,
    ic.FECHAETDREAL_ICARGA AS FECHA_REAL_ETD,
    ic.FECHAETAREAL_ICARGA AS FECHA_REAL_ETA,
    des.TERMOGRAFO_DESPACHOEX AS TERMOGRAFO_DESPACHO,
    exi.N_TERMOGRAFO AS TERMOGRAFO_PALLET,
    des.ID_EMPRESA,
    des.ID_PLANTA,
    des.ID_TEMPORADA,
    esp.ID_ESPECIES,
    exi.ID_VESPECIES,
    exi.ID_PRODUCTOR,
    exi.ID_ICARGA
FROM fruta_exiexportacion exi
INNER JOIN fruta_despachoex des ON des.ID_DESPACHOEX = exi.ID_DESPACHOEX
LEFT JOIN (
    SELECT
        ID_EXIEXPORTACION,
        MAX(FOB_REFERENCIA_CAJA) AS FOB_REFERENCIA_CAJA,
        MAX(FOB_REFERENCIA_KG) AS FOB_REFERENCIA_KG,
        MAX(FOB_VENTA_CAJA) AS FOB_VENTA_CAJA,
        MAX(FOB_VENTA_KG) AS FOB_VENTA_KG,
        SUM(VENTA_USD) AS VENTA_USD,
        SUM(VENTA_USD_BRUTO) AS VENTA_USD_BRUTO,
        SUM(VENTA_USD_NETO) AS VENTA_USD_NETO,
        SUM(RETORNO_NETO) AS RETORNO_NETO,
        MAX(FOB_FINAL_KG) AS FOB_FINAL_KG,
        MAX(FOB_FINAL_CAJA) AS FOB_FINAL_CAJA,
        MAX(NUMERO_VALOR) AS NUMERO_VALOR,
        MAX(FECHA_VALOR) AS FECHA_VALOR,
        MAX(ESTADO_LIQUIDACION) AS ESTADO_LIQUIDACION
    FROM view_liquidacion_exportacion
    GROUP BY ID_EXIEXPORTACION
) liq ON liq.ID_EXIEXPORTACION = exi.ID_EXIEXPORTACION
LEFT JOIN (
    SELECT
        inv.ID_ICARGA,
        det.ID_ESTANDAR,
        det.ID_VESPECIES,
        det.ID_TCALIBRE,
        MAX(det.PRECIO_CAJA) AS PRECIO_CAJA_INVOICE,
        SUM(det.TOTAL_LINEA) AS TOTAL_LINEA_INVOICE,
        MAX(inv.NUMERO_INVOICE) AS NUMERO_INVOICE,
        MAX(inv.MONEDA_INVOICE) AS MONEDA_INVOICE
    FROM exportadora_invoice_detalle det
    INNER JOIN exportadora_invoice inv ON inv.ID_INVOICE = det.ID_INVOICE
    WHERE det.ESTADO_REGISTRO = 1
      AND inv.ESTADO_REGISTRO = 1
    GROUP BY inv.ID_ICARGA, det.ID_ESTANDAR, det.ID_VESPECIES, det.ID_TCALIBRE
) inv ON inv.ID_ICARGA = exi.ID_ICARGA
     AND inv.ID_ESTANDAR = exi.ID_ESTANDAR
     AND inv.ID_VESPECIES = exi.ID_VESPECIES
     AND inv.ID_TCALIBRE = exi.ID_TCALIBRE
LEFT JOIN fruta_icarga ic ON ic.ID_ICARGA = exi.ID_ICARGA
LEFT JOIN estandar_eexportacion est ON est.ID_ESTANDAR = exi.ID_ESTANDAR
LEFT JOIN fruta_productor prod ON prod.ID_PRODUCTOR = exi.ID_PRODUCTOR
LEFT JOIN fruta_vespecies vesp ON vesp.ID_VESPECIES = exi.ID_VESPECIES
LEFT JOIN fruta_especies esp ON esp.ID_ESPECIES = vesp.ID_ESPECIES
LEFT JOIN fruta_tmanejo tm ON tm.ID_TMANEJO = exi.ID_TMANEJO
LEFT JOIN fruta_tcalibre tc ON tc.ID_TCALIBRE = exi.ID_TCALIBRE
LEFT JOIN fruta_tembalaje tem ON tem.ID_TEMBALAJE = exi.ID_TEMBALAJE
LEFT JOIN transporte_transporte trans ON trans.ID_TRANSPORTE = des.ID_TRANSPORTE
LEFT JOIN transporte_conductor cond ON cond.ID_CONDUCTOR = des.ID_CONDUCTOR
LEFT JOIN principal_empresa emp ON emp.ID_EMPRESA = des.ID_EMPRESA
LEFT JOIN principal_planta planta ON planta.ID_PLANTA = des.ID_PLANTA
LEFT JOIN principal_temporada temp ON temp.ID_TEMPORADA = des.ID_TEMPORADA
LEFT JOIN fruta_dfinal dfinal ON dfinal.ID_DFINAL = des.ID_DFINAL
LEFT JOIN fruta_mercado mercado ON mercado.ID_MERCADO = COALESCE(ic.ID_MERCADO, des.ID_MERCADO)
LEFT JOIN fruta_broker broker ON broker.ID_BROKER = ic.ID_BROKER
LEFT JOIN fruta_rfinal rfinal ON rfinal.ID_RFINAL = COALESCE(des.ID_RFINAL, ic.ID_RFINAL)
WHERE exi.ESTADO_REGISTRO = 1
  AND exi.ESTADO IN (7, 8)
  AND des.ESTADO_REGISTRO = 1
  AND des.ID_EMPRESA <> 5;
