CREATE TABLE IF NOT EXISTS fruta_productor_vespecies (
    ID_PRODUCTOR_VESPECIES BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_PRODUCTOR BIGINT(20) NOT NULL,
    ID_VESPECIES BIGINT(20) NOT NULL,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    INGRESO DATETIME DEFAULT NULL,
    MODIFICACION DATETIME DEFAULT NULL,
    ID_USUARIOI BIGINT(20) NOT NULL,
    ID_USUARIOM BIGINT(20) NOT NULL,
    PRIMARY KEY (ID_PRODUCTOR_VESPECIES),
    UNIQUE KEY uq_productor_vespecies (ID_PRODUCTOR, ID_VESPECIES, ID_EMPRESA),
    KEY idx_productor_vespecies_productor (ID_EMPRESA, ID_PRODUCTOR, ESTADO_REGISTRO),
    KEY idx_productor_vespecies_vespecies (ID_EMPRESA, ID_VESPECIES, ESTADO_REGISTRO)
);

CREATE TABLE IF NOT EXISTS fruta_productor_mercado (
    ID_PRODUCTOR_MERCADO BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_PRODUCTOR BIGINT(20) NOT NULL,
    ID_MERCADO BIGINT(20) NOT NULL,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    INGRESO DATETIME DEFAULT NULL,
    MODIFICACION DATETIME DEFAULT NULL,
    ID_USUARIOI BIGINT(20) NOT NULL,
    ID_USUARIOM BIGINT(20) NOT NULL,
    PRIMARY KEY (ID_PRODUCTOR_MERCADO),
    UNIQUE KEY uq_productor_mercado (ID_PRODUCTOR, ID_MERCADO, ID_EMPRESA),
    KEY idx_productor_mercado_productor (ID_EMPRESA, ID_PRODUCTOR, ESTADO_REGISTRO),
    KEY idx_productor_mercado_mercado (ID_EMPRESA, ID_MERCADO, ESTADO_REGISTRO)
);
