CREATE TABLE IF NOT EXISTS fruta_pallet (
    ID_PALLET BIGINT(20) NOT NULL AUTO_INCREMENT,
    TOKEN_QR VARCHAR(120) NOT NULL,
    CSG_PRODUCTOR INT(11) NULL,
    ID_PRODUCTOR BIGINT(20) NULL,
    ID_VESPECIES BIGINT(20) NULL,
    FOLIO_PRODUCTOR BIGINT(20) NULL,
    ID_DRECEPCIONMP BIGINT(20) NULL,
    ID_EXIMATERIAPRIMA BIGINT(20) NULL,
    ID_EMPRESA BIGINT(20) NULL,
    ID_PLANTA BIGINT(20) NULL,
    ID_TEMPORADA BIGINT(20) NULL,
    ESTADO_REGISTRO INT(11) NULL DEFAULT 1,
    INGRESO DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICACION DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_PALLET),
    UNIQUE KEY UK_FRUTA_PALLET_TOKEN (TOKEN_QR),
    KEY IDX_FRUTA_PALLET_QR (CSG_PRODUCTOR, ID_VESPECIES, FOLIO_PRODUCTOR),
    KEY IDX_FRUTA_PALLET_RECEPCION (ID_DRECEPCIONMP),
    KEY IDX_FRUTA_PALLET_EXISTENCIA (ID_EXIMATERIAPRIMA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fruta_pallet_evento (
    ID_EVENTO BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_PALLET BIGINT(20) NOT NULL,
    TIPO_EVENTO VARCHAR(40) NOT NULL,
    FECHA_HORA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO BIGINT(20) NULL,
    ID_EMPRESA BIGINT(20) NULL,
    ID_PLANTA BIGINT(20) NULL,
    ID_TEMPORADA BIGINT(20) NULL,
    OBSERVACION VARCHAR(300) NULL,
    ORIGEN VARCHAR(40) NULL DEFAULT 'WEB',
    ESTADO_REGISTRO INT(11) NULL DEFAULT 1,
    PRIMARY KEY (ID_EVENTO),
    KEY IDX_FRUTA_PALLET_EVENTO_PALLET (ID_PALLET, TIPO_EVENTO, ESTADO_REGISTRO),
    CONSTRAINT FK_FRUTA_PALLET_EVENTO_PALLET
        FOREIGN KEY (ID_PALLET) REFERENCES fruta_pallet (ID_PALLET)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
