ALTER TABLE liquidacion_valor
    ADD COLUMN CONDICION_FLETE VARCHAR(10) NOT NULL DEFAULT 'COLLECT' AFTER FECHA_TIPO_CAMBIO;

ALTER TABLE liquidacion_titem
    ADD COLUMN TIPO_GASTO VARCHAR(20) NOT NULL DEFAULT 'GASTO' AFTER NOMBRE_TITEM;

UPDATE liquidacion_valor val
INNER JOIN fruta_icarga i ON i.ID_ICARGA = val.ID_ICARGA
LEFT JOIN fruta_tflete tf ON tf.ID_TFLETE = i.ID_TFLETE
SET val.CONDICION_FLETE = CASE
    WHEN UPPER(IFNULL(tf.NOMBRE_TFLETE, '')) LIKE '%PREPAID%' THEN 'PREPAID'
    ELSE 'COLLECT'
END;

UPDATE liquidacion_titem
SET TIPO_GASTO = 'COMISION'
WHERE TAITEM = 1
AND UPPER(NOMBRE_TITEM) LIKE '%COMISI%';

UPDATE liquidacion_titem
SET TIPO_GASTO = 'FLETE'
WHERE TAITEM = 1
AND (
    UPPER(NOMBRE_TITEM) LIKE '%FREIGHT%'
    OR UPPER(NOMBRE_TITEM) LIKE '%FLETE%'
);
