CREATE TABLE IF NOT EXISTS fruta_calidad_score_grupo_variedad (
    ID_CALIDAD_SCORE_GRUPO_VARIEDAD BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ID_TEMPORADA BIGINT(20) NOT NULL,
    ID_ESPECIES BIGINT(20) NOT NULL,
    GRUPO_SCORE VARCHAR(30) NOT NULL,
    NOMBRE_VARIEDAD VARCHAR(150) NOT NULL,
    NOMBRE_NORMALIZADO VARCHAR(150) NOT NULL,
    ID_USUARIOI BIGINT(20) NULL,
    ID_USUARIOM BIGINT(20) NULL,
    INGRESO DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICACION DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CALIDAD_SCORE_GRUPO_VARIEDAD),
    UNIQUE KEY UK_CALIDAD_SCORE_GRUPO_VARIEDAD (ID_EMPRESA, ID_TEMPORADA, ID_ESPECIES, NOMBRE_NORMALIZADO),
    KEY IDX_CALIDAD_SCORE_GRUPO_VARIEDAD (ID_EMPRESA, ID_TEMPORADA, ID_ESPECIES, GRUPO_SCORE, ESTADO_REGISTRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fruta_calidad_score_regla (
    ID_CALIDAD_SCORE_REGLA BIGINT(20) NOT NULL AUTO_INCREMENT,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ID_TEMPORADA BIGINT(20) NOT NULL,
    ID_ESPECIES BIGINT(20) NOT NULL,
    GRUPO_SCORE VARCHAR(30) NOT NULL,
    GRUPO_PARAMETRO VARCHAR(40) NOT NULL,
    NOMBRE_PARAMETRO VARCHAR(150) NOT NULL,
    NOMBRE_NORMALIZADO VARCHAR(150) NOT NULL,
    SCORE INT(11) NOT NULL,
    SCORE_NOMBRE VARCHAR(60) NULL,
    OPERADOR VARCHAR(5) NOT NULL,
    VALOR DECIMAL(12,4) NOT NULL,
    INCLUYE_IGUAL TINYINT(1) NOT NULL DEFAULT 0,
    ES_PORCENTAJE TINYINT(1) NOT NULL DEFAULT 1,
    ID_USUARIOI BIGINT(20) NULL,
    ID_USUARIOM BIGINT(20) NULL,
    INGRESO DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICACION DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CALIDAD_SCORE_REGLA),
    UNIQUE KEY UK_CALIDAD_SCORE_REGLA (ID_EMPRESA, ID_TEMPORADA, ID_ESPECIES, GRUPO_SCORE, NOMBRE_NORMALIZADO, SCORE),
    KEY IDX_CALIDAD_SCORE_REGLA_BUSQUEDA (ID_EMPRESA, ID_TEMPORADA, ID_ESPECIES, GRUPO_SCORE, NOMBRE_NORMALIZADO, ESTADO_REGISTRO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE fruta_calidad_control
    ADD COLUMN IF NOT EXISTS SCORE_GENERAL DECIMAL(12,4) NULL AFTER PORC_ESTIMADO_EXPORTACION,
    ADD COLUMN IF NOT EXISTS GRUPO_SCORE VARCHAR(30) NULL AFTER SCORE_GENERAL;
