DROP VIEW IF EXISTS view_recepciones;

CREATE ALGORITHM=UNDEFINED SQL SECURITY INVOKER VIEW view_recepciones AS
SELECT
    'RECEPCION_MP' AS TIPO_REPORTE,
    R.ID_RECEPCION,
    D.ID_DRECEPCION,
    R.NUMERO_RECEPCION AS PROCESO,
    R.NUMERO_RECEPCION,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'PRODUCTOR'
        WHEN R.TRECEPCION = 2 THEN 'PLANTA EXTERNA'
        WHEN R.TRECEPCION = 3 THEN 'OTROS'
        ELSE 'DESCONOCIDO'
    END AS TIPO,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'Desde Productor '
        WHEN R.TRECEPCION = 2 THEN 'Planta Externa'
        WHEN R.TRECEPCION = 3 THEN 'Desde Productor BDH'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    R.FECHA_RECEPCION AS FECHA,
    R.FECHA_RECEPCION,
    R.FECHA_GUIA_RECEPCION AS FECHAG,
    R.FECHA_GUIA_RECEPCION,
    R.HORA_RECEPCION AS HORA,
    R.NUMERO_GUIA_RECEPCION AS GUIA,
    R.NUMERO_GUIA_RECEPCION,
    D.FOLIO_DRECEPCION AS FOLIO,
    D.FOLIO_DRECEPCION,
    D.FECHA_COSECHA_DRECEPCION AS FECHA_DETALLE,
    D.FECHA_COSECHA_DRECEPCION AS COSECHA,
    NULL AS EMBALADO,
    'MATERIA PRIMA' AS ORIGEN,
    'Materia Prima' AS TIPO_PRODUCTO,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS KILOS,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS CANTIDAD,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS ENVASE,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS NETO,
    NULL AS NETO_REAL,
    IFNULL(D.KILOS_BRUTO_DRECEPCION, 0) AS BRUTO,
    NULL AS PORCENTAJE_DESHIDRATACION,
    NULL AS KILOS_DESHIDRATACION,
    IFNULL(ER.CODIGO_ESTANDAR, 'Sin Datos') AS CODIGO_ESTANDAR,
    IFNULL(ER.NOMBRE_ESTANDAR, 'Sin Datos') AS NOMBRE_ESTANDAR,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS VARIEDAD,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS NOMBRE_VESPECIES,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS PRODUCTOR,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS NOMBRE_PRODUCTOR,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG_PRODUCTOR,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS ESPECIE,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS NOMBRE_ESPECIES,
    CASE
        WHEN R.TRECEPCION IN (1, 3) THEN IFNULL(CONCAT(ORIG_PROD.CSG_PRODUCTOR, ':', ORIG_PROD.NOMBRE_PRODUCTOR), 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS TIPO_MANEJO,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS NOMBRE_TMANEJO,
    'Sin Datos' AS TIPO_CALIBRE,
    'Sin Datos' AS TIPO_EMBALAJE,
    'Sin Datos' AS STOCK,
    'Sin Datos' AS EMBOLSADO,
    CASE
        WHEN D.GASIFICADO_DRECEPCION = 1 THEN 'SI'
        WHEN D.GASIFICADO_DRECEPCION = 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS GASIFICACION,
    'Sin Datos' AS PREFRIO,
    IFNULL(TT1.NOMBRE_TTRATAMIENTO, 'Sin Datos') AS TRATAMIENTO1,
    IFNULL(TT2.NOMBRE_TTRATAMIENTO, 'Sin Datos') AS CUARTEL,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS TRANSPORTE,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    R.PATENTE_CAMION,
    R.PATENTE_CARRO,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    WEEKOFYEAR(R.FECHA_RECEPCION) AS SEMANAISO,
    WEEKOFYEAR(R.FECHA_GUIA_RECEPCION) AS SEMANAGUIAISO,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS PLANTA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS TEMPORADA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS EMPRESA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    D.ID_PRODUCTOR,
    R.ID_PRODUCTOR AS ID_PRODUCTOR_RECEPCION,
    R.ID_PLANTA2,
    R.ID_PLANTA,
    ESP.ID_ESPECIES,
    VES.ID_VESPECIES,
    R.ID_TEMPORADA,
    R.ID_EMPRESA,
    D.ID_ESTANDAR,
    D.ID_TMANEJO,
    NULL AS ID_TCALIBRE,
    NULL AS ID_TEMBALAJE,
    D.ID_TTRATAMIENTO1,
    D.ID_TTRATAMIENTO2,
    R.INGRESO,
    R.MODIFICACION
FROM fruta_recepcionmp R
INNER JOIN fruta_drecepcionmp D ON D.ID_RECEPCION = R.ID_RECEPCION AND D.ESTADO_REGISTRO = 1
LEFT JOIN fruta_productor PROD ON PROD.ID_PRODUCTOR = D.ID_PRODUCTOR
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
LEFT JOIN fruta_vespecies VES ON VES.ID_VESPECIES = D.ID_VESPECIES
LEFT JOIN fruta_especies ESP ON ESP.ID_ESPECIES = VES.ID_ESPECIES
LEFT JOIN estandar_erecepcion ER ON ER.ID_ESTANDAR = D.ID_ESTANDAR
LEFT JOIN fruta_tmanejo TM ON TM.ID_TMANEJO = D.ID_TMANEJO
LEFT JOIN fruta_tratamineto1 TT1 ON TT1.ID_TTRATAMIENTO = D.ID_TTRATAMIENTO1
LEFT JOIN fruta_tratamineto2 TT2 ON TT2.ID_TTRATAMIENTO = D.ID_TTRATAMIENTO2
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
WHERE R.ESTADO_REGISTRO = 1
  AND R.ID_EMPRESA <> 5

UNION ALL

SELECT
    'RECEPCION_IND' AS TIPO_REPORTE,
    R.ID_RECEPCION,
    D.ID_DRECEPCION,
    R.NUMERO_RECEPCION AS PROCESO,
    R.NUMERO_RECEPCION,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'PRODUCTOR'
        WHEN R.TRECEPCION = 2 THEN 'PLANTA EXTERNA'
        WHEN R.TRECEPCION = 3 THEN 'OTROS'
        ELSE 'DESCONOCIDO'
    END AS TIPO,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'Desde Productor '
        WHEN R.TRECEPCION = 2 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    R.FECHA_RECEPCION AS FECHA,
    R.FECHA_RECEPCION,
    R.FECHA_GUIA_RECEPCION AS FECHAG,
    R.FECHA_GUIA_RECEPCION,
    R.HORA_RECEPCION AS HORA,
    R.NUMERO_GUIA_RECEPCION AS GUIA,
    R.NUMERO_GUIA_RECEPCION,
    D.FOLIO_DRECEPCION AS FOLIO,
    D.FOLIO_DRECEPCION,
    D.FECHA_EMBALADO_DRECEPCION AS FECHA_DETALLE,
    NULL AS COSECHA,
    D.FECHA_EMBALADO_DRECEPCION AS EMBALADO,
    'IND. HUERTO' AS ORIGEN,
    'Producto Industrial' AS TIPO_PRODUCTO,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS KILOS,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS CANTIDAD,
    IFNULL(D.CANTIDAD_ENVASE_DRECEPCION, 0) AS ENVASE,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS NETO,
    NULL AS NETO_REAL,
    IFNULL(D.KILOS_BRUTO_DRECEPCION, 0) AS BRUTO,
    NULL AS PORCENTAJE_DESHIDRATACION,
    NULL AS KILOS_DESHIDRATACION,
    IFNULL(EI.CODIGO_ESTANDAR, 'Sin Datos') AS CODIGO_ESTANDAR,
    IFNULL(EI.NOMBRE_ESTANDAR, 'Sin Datos') AS NOMBRE_ESTANDAR,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS VARIEDAD,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS NOMBRE_VESPECIES,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS PRODUCTOR,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS NOMBRE_PRODUCTOR,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG_PRODUCTOR,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS ESPECIE,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS NOMBRE_ESPECIES,
    CASE
        WHEN R.TRECEPCION = 1 THEN IFNULL(CONCAT(ORIG_PROD.CSG_PRODUCTOR, ':', ORIG_PROD.NOMBRE_PRODUCTOR), 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS TIPO_MANEJO,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS NOMBRE_TMANEJO,
    'Sin Datos' AS TIPO_CALIBRE,
    'Sin Datos' AS TIPO_EMBALAJE,
    'Sin Datos' AS STOCK,
    'Sin Datos' AS EMBOLSADO,
    'Sin Datos' AS GASIFICACION,
    'Sin Datos' AS PREFRIO,
    'Sin Datos' AS TRATAMIENTO1,
    'Sin Datos' AS CUARTEL,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS TRANSPORTE,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    R.PATENTE_CAMION,
    R.PATENTE_CARRO,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    WEEKOFYEAR(R.FECHA_RECEPCION) AS SEMANAISO,
    WEEKOFYEAR(R.FECHA_GUIA_RECEPCION) AS SEMANAGUIAISO,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS PLANTA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS TEMPORADA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS EMPRESA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    D.ID_PRODUCTOR,
    R.ID_PRODUCTOR AS ID_PRODUCTOR_RECEPCION,
    R.ID_PLANTA2,
    R.ID_PLANTA,
    ESP.ID_ESPECIES,
    VES.ID_VESPECIES,
    R.ID_TEMPORADA,
    R.ID_EMPRESA,
    D.ID_ESTANDAR,
    D.ID_TMANEJO,
    NULL AS ID_TCALIBRE,
    NULL AS ID_TEMBALAJE,
    NULL AS ID_TTRATAMIENTO1,
    NULL AS ID_TTRATAMIENTO2,
    R.INGRESO,
    R.MODIFICACION
FROM fruta_recepcionind R
INNER JOIN fruta_drecepcionind D ON D.ID_RECEPCION = R.ID_RECEPCION AND D.ESTADO_REGISTRO = 1
LEFT JOIN fruta_productor PROD ON PROD.ID_PRODUCTOR = D.ID_PRODUCTOR
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
LEFT JOIN fruta_vespecies VES ON VES.ID_VESPECIES = D.ID_VESPECIES
LEFT JOIN fruta_especies ESP ON ESP.ID_ESPECIES = VES.ID_ESPECIES
LEFT JOIN estandar_eindustrial EI ON EI.ID_ESTANDAR = D.ID_ESTANDAR
LEFT JOIN fruta_tmanejo TM ON TM.ID_TMANEJO = D.ID_TMANEJO
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
WHERE R.ESTADO_REGISTRO = 1
  AND R.ID_EMPRESA <> 5

UNION ALL

SELECT
    'RECEPCION_PT' AS TIPO_REPORTE,
    R.ID_RECEPCION,
    D.ID_DRECEPCION,
    R.NUMERO_RECEPCION AS PROCESO,
    R.NUMERO_RECEPCION,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'PRODUCTOR'
        WHEN R.TRECEPCION = 2 THEN 'PLANTA EXTERNA'
        WHEN R.TRECEPCION = 3 THEN 'OTROS'
        ELSE 'DESCONOCIDO'
    END AS TIPO,
    CASE
        WHEN R.TRECEPCION = 1 THEN 'Desde Productor '
        WHEN R.TRECEPCION = 2 THEN 'Planta Externa'
        ELSE 'Sin Datos'
    END AS TIPO_RECEPCION,
    R.FECHA_RECEPCION AS FECHA,
    R.FECHA_RECEPCION,
    R.FECHA_GUIA_RECEPCION AS FECHAG,
    R.FECHA_GUIA_RECEPCION,
    R.HORA_RECEPCION AS HORA,
    R.NUMERO_GUIA_RECEPCION AS GUIA,
    R.NUMERO_GUIA_RECEPCION,
    D.FOLIO_DRECEPCION AS FOLIO,
    D.FOLIO_DRECEPCION,
    D.FECHA_EMBALADO_DRECEPCION AS FECHA_DETALLE,
    NULL AS COSECHA,
    D.FECHA_EMBALADO_DRECEPCION AS EMBALADO,
    'PRODUCTO TERMINADO' AS ORIGEN,
    'Producto Terminado' AS TIPO_PRODUCTO,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS KILOS,
    IFNULL(D.CANTIDAD_ENVASE_APROBADO_DRECEPCION, 0) AS CANTIDAD,
    IFNULL(D.CANTIDAD_ENVASE_APROBADO_DRECEPCION, 0) AS ENVASE,
    IFNULL(D.KILOS_NETO_DRECEPCION, 0) AS NETO,
    IFNULL(D.KILOS_NETO_REAL_DRECEPCION, 0) AS NETO_REAL,
    IFNULL(D.KILOS_BRUTO_DRECEPCION, 0) AS BRUTO,
    IFNULL(D.PDESHIDRATACION_DRECEPCION, 0) AS PORCENTAJE_DESHIDRATACION,
    IFNULL(D.KILOS_DESHIDRATACION_DRECEPCION, 0) AS KILOS_DESHIDRATACION,
    IFNULL(EE.CODIGO_ESTANDAR, 'Sin Datos') AS CODIGO_ESTANDAR,
    IFNULL(EE.NOMBRE_ESTANDAR, 'Sin Datos') AS NOMBRE_ESTANDAR,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS VARIEDAD,
    IFNULL(VES.NOMBRE_VESPECIES, 'Sin Datos') AS NOMBRE_VESPECIES,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS PRODUCTOR,
    IFNULL(PROD.NOMBRE_PRODUCTOR, 'Sin Datos') AS NOMBRE_PRODUCTOR,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG,
    IFNULL(PROD.CSG_PRODUCTOR, 'Sin Datos') AS CSG_PRODUCTOR,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS ESPECIE,
    IFNULL(ESP.NOMBRE_ESPECIES, 'Sin Datos') AS NOMBRE_ESPECIES,
    CASE
        WHEN R.TRECEPCION = 1 THEN IFNULL(CONCAT(ORIG_PROD.CSG_PRODUCTOR, ':', ORIG_PROD.NOMBRE_PRODUCTOR), 'Sin Datos')
        WHEN R.TRECEPCION = 2 THEN IFNULL(ORIG_PLANTA.NOMBRE_PLANTA, 'Sin Datos')
        ELSE 'Sin Datos'
    END AS ORIGEN_RECEPCION,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS TIPO_MANEJO,
    IFNULL(TM.NOMBRE_TMANEJO, 'Sin Datos') AS NOMBRE_TMANEJO,
    IFNULL(TC.NOMBRE_TCALIBRE, 'Sin Datos') AS TIPO_CALIBRE,
    IFNULL(TE.NOMBRE_TEMBALAJE, 'Sin Datos') AS TIPO_EMBALAJE,
    CASE
        WHEN D.STOCK_DRECEPCION = 1 THEN 'SI'
        WHEN D.STOCK_DRECEPCION = 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS STOCK,
    CASE
        WHEN D.EMBOLSADO_DRECEPCION = 1 THEN 'SI'
        WHEN D.EMBOLSADO_DRECEPCION = 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS EMBOLSADO,
    CASE
        WHEN D.GASIFICADO_DRECEPCION = 1 THEN 'SI'
        WHEN D.GASIFICADO_DRECEPCION = 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS GASIFICACION,
    CASE
        WHEN D.PREFRIO_DRECEPCION = 1 THEN 'SI'
        WHEN D.PREFRIO_DRECEPCION = 0 THEN 'NO'
        ELSE 'Sin Datos'
    END AS PREFRIO,
    'Sin Datos' AS TRATAMIENTO1,
    'Sin Datos' AS CUARTEL,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS TRANSPORTE,
    IFNULL(TR.NOMBRE_TRANSPORTE, 'Sin Datos') AS NOMBRE_TRANSPORTE,
    IFNULL(CO.NOMBRE_CONDUCTOR, 'Sin Datos') AS NOMBRE_CONDUCTOR,
    R.PATENTE_CAMION,
    R.PATENTE_CARRO,
    WEEK(R.FECHA_RECEPCION, 3) AS SEMANA,
    WEEK(R.FECHA_GUIA_RECEPCION, 3) AS SEMANAGUIA,
    WEEKOFYEAR(R.FECHA_RECEPCION) AS SEMANAISO,
    WEEKOFYEAR(R.FECHA_GUIA_RECEPCION) AS SEMANAGUIAISO,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS PLANTA,
    IFNULL(PLA.NOMBRE_PLANTA, 'Sin Datos') AS NOMBRE_PLANTA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS TEMPORADA,
    IFNULL(TEM.NOMBRE_TEMPORADA, 'Sin Datos') AS NOMBRE_TEMPORADA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS EMPRESA,
    IFNULL(EMP.NOMBRE_EMPRESA, 'Sin Datos') AS NOMBRE_EMPRESA,
    D.ID_PRODUCTOR,
    R.ID_PRODUCTOR AS ID_PRODUCTOR_RECEPCION,
    R.ID_PLANTA2,
    R.ID_PLANTA,
    ESP.ID_ESPECIES,
    VES.ID_VESPECIES,
    R.ID_TEMPORADA,
    R.ID_EMPRESA,
    D.ID_ESTANDAR,
    D.ID_TMANEJO,
    D.ID_TCALIBRE,
    D.ID_TEMBALAJE,
    NULL AS ID_TTRATAMIENTO1,
    NULL AS ID_TTRATAMIENTO2,
    R.INGRESO,
    R.MODIFICACION
FROM fruta_recepcionpt R
INNER JOIN fruta_drecepcionpt D ON D.ID_RECEPCION = R.ID_RECEPCION AND D.ESTADO_REGISTRO = 1
LEFT JOIN fruta_productor PROD ON PROD.ID_PRODUCTOR = D.ID_PRODUCTOR
LEFT JOIN fruta_productor ORIG_PROD ON ORIG_PROD.ID_PRODUCTOR = R.ID_PRODUCTOR
LEFT JOIN principal_planta ORIG_PLANTA ON ORIG_PLANTA.ID_PLANTA = R.ID_PLANTA2
LEFT JOIN principal_planta PLA ON PLA.ID_PLANTA = R.ID_PLANTA
LEFT JOIN principal_empresa EMP ON EMP.ID_EMPRESA = R.ID_EMPRESA
LEFT JOIN principal_temporada TEM ON TEM.ID_TEMPORADA = R.ID_TEMPORADA
LEFT JOIN fruta_vespecies VES ON VES.ID_VESPECIES = D.ID_VESPECIES
LEFT JOIN fruta_especies ESP ON ESP.ID_ESPECIES = VES.ID_ESPECIES
LEFT JOIN estandar_eexportacion EE ON EE.ID_ESTANDAR = D.ID_ESTANDAR
LEFT JOIN fruta_tmanejo TM ON TM.ID_TMANEJO = D.ID_TMANEJO
LEFT JOIN fruta_tcalibre TC ON TC.ID_TCALIBRE = D.ID_TCALIBRE
LEFT JOIN fruta_tembalaje TE ON TE.ID_TEMBALAJE = D.ID_TEMBALAJE
LEFT JOIN transporte_transporte TR ON TR.ID_TRANSPORTE = R.ID_TRANSPORTE
LEFT JOIN transporte_conductor CO ON CO.ID_CONDUCTOR = R.ID_CONDUCTOR
WHERE R.ESTADO_REGISTRO = 1
  AND R.ID_EMPRESA <> 5;
