CREATE TABLE IF NOT EXISTS fruta_calidad_inspector (
    ID_CALIDAD_INSPECTOR BIGINT(20) NOT NULL AUTO_INCREMENT,
    NOMBRE_INSPECTOR VARCHAR(150) NOT NULL,
    ID_EMPRESA BIGINT(20) NOT NULL,
    ID_TEMPORADA BIGINT(20) NOT NULL,
    ID_USUARIOI BIGINT(20) NULL,
    ID_USUARIOM BIGINT(20) NULL,
    INGRESO DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFICACION DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    ESTADO_REGISTRO INT(11) NOT NULL DEFAULT 1,
    PRIMARY KEY (ID_CALIDAD_INSPECTOR),
    KEY IDX_CALIDAD_INSPECTOR_CONTEXTO (ID_EMPRESA, ID_TEMPORADA, ESTADO_REGISTRO),
    KEY IDX_CALIDAD_INSPECTOR_NOMBRE (NOMBRE_INSPECTOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
