ALTER TABLE liquidacion_valor
    ADD COLUMN MONEDA_ORIGEN    VARCHAR(3)     NOT NULL DEFAULT 'USD' AFTER OBSERVACION_VALOR,
    ADD COLUMN TIPO_CAMBIO_USD  DECIMAL(14,6)  NOT NULL DEFAULT 1.000000 AFTER MONEDA_ORIGEN,
    ADD COLUMN FECHA_TIPO_CAMBIO DATE           NULL AFTER TIPO_CAMBIO_USD;
