ALTER TABLE fruta_calidad_parametro
    ADD COLUMN IF NOT EXISTS GRUPO_REPORTE VARCHAR(40) NULL AFTER TIPO_PARAMETRO,
    ADD KEY IF NOT EXISTS IDX_CALIDAD_PARAMETRO_GRUPO (GRUPO_REPORTE, ETAPA, ESTADO_REGISTRO);
