ALTER TABLE fruta_calidad_control
    ADD COLUMN IF NOT EXISTS MUESTRA_GRAMOS DECIMAL(12,4) NULL AFTER ID_USUARIO,
    ADD COLUMN IF NOT EXISTS ID_CALIDAD_INSPECTOR BIGINT(20) NULL AFTER ID_USUARIO,
    ADD COLUMN IF NOT EXISTS PORC_DEFECTO_CONDICION DECIMAL(12,4) NULL AFTER RESULTADO_GENERAL,
    ADD COLUMN IF NOT EXISTS PORC_DEFECTO_CALIDAD DECIMAL(12,4) NULL AFTER PORC_DEFECTO_CONDICION,
    ADD COLUMN IF NOT EXISTS PORC_FIRMEZA DECIMAL(12,4) NULL AFTER PORC_DEFECTO_CALIDAD,
    ADD COLUMN IF NOT EXISTS PORC_ESTIMADO_EXPORTACION DECIMAL(12,4) NULL AFTER PORC_FIRMEZA,
    ADD KEY IF NOT EXISTS IDX_CALIDAD_CONTROL_INSPECTOR (ID_CALIDAD_INSPECTOR);
